### PR TITLE
Fix some bugs (GCC gave me warnings).

### PR DESCRIPTION
**Pull request by novalis**
Untested -- check isn't working on my machine.  Wait for travis to confirm.

### CODE REVIEW

**Comment by novalis** [comment]
@mcguigan These just fix some warnings (despite the PR's title).  The warnings are pretty dire tho, and maybe they're real bugs on some platforms.

**Comment by mcguigan** [comment]
All looks fine to me.

**Comment by novalis** [comment]
Cool.  I don't have write access to this repo, so please merge.

**Comment by mcguigan** [comment]
Me neither.  Working on it.

**Pull request merged**
